name: Run Tushare Script

on:
  schedule:
    # 每天的上午 9 点（上海时间）运行
    - cron: "0 14 * * *" # GitHub Actions 使用 UTC 时间，1 点对应上海时间 9 点
  workflow_dispatch: # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 运行脚本
    - name: Run Python Script
      env:
        API_KEY: ${{ secrets.TS_TOKEN }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python usd.py
